version: '3.8'

services:
  db:
    container_name: pg_movies
    build:
      context: ./sqlite_to_postgres/postgres
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: always

  load_data:
    container_name: to_postgres
    build:
      context: ./sqlite_to_postgres/sqlite_to_postgres
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  elasticsearch:
    container_name: es-movies
    image: elasticsearch:8.9.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - bootstrap.memory_lock=true
      - ingest.geoip.downloader.enabled=false
      - logger.level=WARN
    expose:
      - ${ES_PORT}
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis:
    container_name: redis-movies
    image: redis:7.2.3-alpine3.19
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    command: redis-server --save 60 1 --loglevel notice

  etl:
    container_name: etl_movies
    build:
      context: ./etl
    env_file:
      - .env
    volumes:
      - etl_log:/app/logs
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: always

  movies_fastapi:
    container_name: movies_fastapi
    build:
      context: ./movies_fastapi
    env_file:
      - .env
    expose:
      - ${PROJECT_PORT}
    volumes:
      - fastapi_log:/usr/src/movies_fastapi/logs
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b :8000 main:app

  nginx:
    container_name: nginx
    image: nginx:1.25-bookworm
    ports:
      - ${NGINX_PORT_OUT}:${NGINX_PORT}
    volumes:
      - nginx_log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - movies_fastapi
    restart: always

volumes:
  postgres_data:
  etl_log:
  redis_data:
  elastic_data:
  fastapi_log:
  nginx_log:
