version: '3'
services:
  db:
    container_name: pg-movies
    build:
      context: ./sqlite_to_postgres/postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  load_data:
    container_name: to-postgres
    build:
      context: ./sqlite_to_postgres/sqlite_to_postgres
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
