version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: es-movies
    ports:
#      - ${ES_PORT}:${ES_PORT}
      - 9200:9200
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ingest.geoip.downloader.enabled=false
    env_file: ../.env

