version: '3.8'

services:
  db:
    container_name: db
    build:
      context: ./postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  load_data:
    container_name: load_data
    build:
      context: ./sqlite_to_postgres
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: